### ISSUE TITLE
謝謝你的心得

### ISSUE THREAD

**Issue by azole** [kevintom1997/git-workshop#3]
謝謝你的心得。

以下是我給帛賢的建議，也給你參考一下：

> 作為軟體工程師，要學習的東西非常多，除了「輸入」之外，也可以多練習「輸出」，從整理自己聽到、讀到的知識開始，也許現在只能摘要，但可以「刻意」去練習，例如除了摘要之外，用自己的脈絡來理解跟重新編排知識。甚至更棒的是，套用在自己過往的經驗中，如果能將這次學習到的東西跟過往自身的經驗連結在一起，那就可以加快學習的速度、記憶也會更深刻，而這樣學到的東西也會是獨一無二的。
>
> 這樣逐步練習跟累積，慢慢地就可以開始有自己的產出了，記得，聽進去的不是你的，你做得出來、解釋得出來的，才是真正你學會的東西，加油，共勉之。

此外，我的上課方式都還習慣嗎？ 我應該大部分的時候都會試著講解為什麼？ 如果有什麼問題都可以隨時提出來討論喔！

**Comment by kevintom1997** [comment]
感謝老師，因為我19號請假所以是看影片來學習這堂課程，但聽到許多同學跟我說您是他們目前上過最仔細且認真老師，所以我覺得跟著老師學習應該會吸收得更快!!!

**Comment by azole** [comment]
錄影效果好像不是很好，我太愛畫白板了，有任何問題的話，可以再找我討論喔～
